name: Setup matrix
author: Alexander Druz
description: Create reusable dynamic job matrices for your workflows.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    default: ''
    description: Strategy matrix exactly as it would be given to a job.
outputs:
  matrix:
    description: Strategy matrix in JSON format, ready to be used in other jobs.
runs:
  using: docker
  image: Dockerfile
