name: Build Matrix
author: Alexander Druz
description: Create reusable dynamic job matrices for your workflows.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    default: ''
    description: Base matrix
  include:
    default: ''
    description: Extra matrix combinations to include
  exclude:
    default: ''
    description: Matrix combinations to exclude from matrix
outputs:
  matrix:
    description: matrix in JSON format
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Add action folder to PATH
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Set matrix
      id: set-matrix
      run: |
        MATRIX="$(parse-matrix.sh "${{ inputs.matrix }}" "${{ inputs.include }}" "${{ inputs.exclude }}")"
        echo "$MATRIX" | yq -P '{"matrix":.}'
        echo "MATRIX=$MATRIX" >> $GITHUB_ENV
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
      shell: bash
