name: Setup matrix
author: Alexander Druz
description: Create reusable dynamic job matrices for your workflows.
branding:
  icon: layers
  color: gray-dark
inputs:
  matrix:
    default: ''
    description: Base matrix
  include:
    default: ''
    description: Extra matrix combinations to include
  exclude:
    default: ''
    description: Matrix combinations to exclude from matrix
outputs:
  matrix:
    description: matrix in JSON format
runs:
  using: docker
  image: Dockerfile
