name: 1. Basic usage

on: push

jobs:
  # Setup matrix
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - id: setup-matrix
        uses: druzsan/setup-matrix@feature/use-python-dockerfile
        with:
          matrix: |
            fruit: [apple, pear]
            animal: [cat, dog]
          include: |
            - color: green
            - color: pink
              animal: cat
            - fruit: apple
              shape: circle
            - fruit: banana
            - fruit: banana
              animal: cat
  # Setup python and print version
  setup-python:
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - run: python --version
