name: 1. Basic usage

on: push

jobs:
  # Setup matrix
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    env:
      REF: ${{ github.ref_name }}
    steps:
      - run: echo $REF
      - run: echo ${{ env.REF }}
      - id: setup-matrix
        uses: druzsan/setup-matrix@feature/use-python-dockerfile
        with:
          matrix: |
            os: [ubuntu-latest, macos-latest]
            python-version: [3.8, 3.10, 3.12]
            include:
              - os: windows-latest
                python-version: 3.8
              - os: windows-latest
                python-version: 3.10
            exclude:
              - os: macos-latest
                python-version: 3.8
  # Setup python and print version
  setup-python:
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - run: python --version
